name: Publish PHP 8.1 Image
on:
  release:
    types: [published]
      
  workflow_dispatch: {}

jobs:
  build:
    name: Release OCI image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      
    outputs:
      image-refs: ${{ steps.emit-refs.outputs.image-refs }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_LOGIN_USER }}
        password: ${{ secrets.DOCKER_LOGIN_PASS }}
   
    - run: cp $HOME/.docker/config.json .
          
    - uses: cpanato/chainguard-images-actions/apko-snapshot@updates
      with:
        config: php81/apko.yaml
        base-tag: minicli/php81
        archs: x86_64,aarch64,armv7
        package-version-tag: php81
        registry: docker.io        
        username: ${{ secrets.DOCKER_LOGIN_USER }}
        token: ${{ secrets.DOCKER_LOGIN_PASS }}
        image_refs: apko.images

    - name: Emit Image Refs output
      id: emit-refs
      run: |
          cat apko.images | sed 's/$/\n/g' | grep -v '^$' | jq -R -s -c 'split("\n")[:-1]' | jq .
          echo ::set-output name=image-refs::$(cat apko.images | sed 's/$/\n/g' | grep -v '^$' | jq -R -s -c 'split("\n")[:-1]')
