name: Publish minicli/php81-dev Image
on:
  release:
    types: [published]
  
  schedule: 
    - cron: "0 2 * * *"
  
  workflow_dispatch: {}

jobs:
  build:
    name: Release OCI image
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_LOGIN_USER }}
        password: ${{ secrets.DOCKER_LOGIN_PASS }}
   
    - run: cp $HOME/.docker/config.json .
          
    - uses: cpanato/chainguard-images-actions/apko-snapshot@updates
      with:
        config: php81-dev/apko.yaml
        base-tag: minicli/php81-dev
        package-version-tag: 8.1
        registry: docker.io        
        username: ${{ secrets.DOCKER_LOGIN_USER }}
        token: ${{ secrets.DOCKER_LOGIN_PASS }}
        image_refs: apko.images
